import { useCallback, useEffect, useState } from "react";
import { api } from "../api";
import type { DataSource, KnowledgeBase } from "../types";
import { Modal } from "./Modal";

const INDEX_LABEL = { idle: "未索引", queued: "等待索引", running: "索引中", succeeded: "索引完成", failed: "索引失败" } as const;
function bytes(value: number) { if (!value) return "0 KB"; const unit = value >= 1024 ** 3 ? [1024 ** 3, "GB"] : value >= 1024 ** 2 ? [1024 ** 2, "MB"] : [1024, "KB"]; return `${(value / Number(unit[0])).toFixed(1)} ${unit[1]}`; }

export function DataSourcesPage({ onOpen }: { onOpen: (path: string) => void }) {
  const [items, setItems] = useState<DataSource[] | null>(null); const [bases, setBases] = useState<KnowledgeBase[]>([]);
  const [knowledgeBaseId, setKnowledgeBaseId] = useState("kb_default"); const [uploading, setUploading] = useState(false);
  const [confirmDelete, setConfirmDelete] = useState<DataSource | null>(null); const [error, setError] = useState("");
  const [notice, setNotice] = useState(""); const [updatingId, setUpdatingId] = useState("");
  const [page, setPage] = useState(0); const [hasNext, setHasNext] = useState(false); const pageSize = 20;
  const load = useCallback(async () => { setError(""); try { const [sources, knowledgeBases] = await Promise.all([api.listDataSources(page * pageSize, pageSize + 1), api.listKnowledgeBases()]); setHasNext(sources.length > pageSize); setItems(sources.slice(0, pageSize)); setBases(knowledgeBases); if (!knowledgeBases.some((item) => item.knowledge_base_id === knowledgeBaseId) && knowledgeBases[0]) setKnowledgeBaseId(knowledgeBases[0].knowledge_base_id); } catch (reason) { setError(reason instanceof Error ? reason.message : "无法读取数据源。"); setItems([]); } }, [knowledgeBaseId, page]);
  useEffect(() => { void Promise.resolve().then(load); }, [load]);
  const hasActiveIndexing = items?.some((item) => item.index_status === "queued" || item.index_status === "running") ?? false;
  useEffect(() => {
    if (!hasActiveIndexing) return undefined;
    const timer = window.setInterval(() => { void load(); }, 1_000);
    return () => window.clearInterval(timer);
  }, [hasActiveIndexing, load]);
  const upload = async (file: File) => { setUploading(true); setError(""); setNotice(""); try { const result = await api.uploadKnowledgeBaseDocument(knowledgeBaseId, file); setNotice(result.status === "ready" ? `“${file.name}”上传成功，内容未变化。` : `“${file.name}”上传成功，等待索引。`); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "上传失败。"); } finally { setUploading(false); } };
  const act = async (action: () => Promise<unknown>) => { setError(""); try { await action(); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "操作失败。"); } };
  const updateFile = async (item: DataSource, file: File) => { setError(""); setNotice(""); if (file.name !== item.name) { setError(`请选择同名文件“${item.name}”，避免意外创建新的数据源。`); return; } setUpdatingId(item.data_source_id); try { const result = await api.uploadKnowledgeBaseDocument(item.knowledge_base_id, file); setNotice(result.status === "ready" ? `“${item.name}”内容未变化，无需创建新版本。` : `“${item.name}”的新版本已上传并加入索引队列。`); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "文件更新失败。"); } finally { setUpdatingId(""); } };
  return <section className="product-page" aria-label="数据源管理">
    <div className="management-toolbar data-source-toolbar"><select aria-label="上传到知识库" value={knowledgeBaseId} onChange={(event) => setKnowledgeBaseId(event.target.value)}>{bases.map((item) => <option key={item.knowledge_base_id} value={item.knowledge_base_id}>{item.name}</option>)}</select><label className="primary-action upload-source">{uploading ? "上传中…" : "＋ 文件数据源"}<input type="file" disabled={uploading || !bases.length} accept=".pdf,.docx,.txt,.md,.html,.htm,.xlsx,.csv" onChange={(event) => { const file = event.target.files?.[0]; if (file) void upload(file); event.currentTarget.value = ""; }}/></label></div>
    {error ? <div className="error-banner" role="alert">{error} <button onClick={() => void load()}>重试</button></div> : null}
    {notice ? <div className="success-banner" role="status">{notice}</div> : null}
    {items === null ? <div className="evaluation-state pulse">正在读取数据源…</div> : null}
    {items?.length === 0 && !error ? <div className="evaluation-state"><h2>还没有数据源</h2><p>选择知识库并上传文件，系统将创建可追溯的文件数据源。</p></div> : null}
    {items?.length ? <div className="management-table-wrap"><table className="management-table data-source-table"><thead><tr><th>数据源</th><th>所属知识库</th><th>上传状态</th><th>索引状态</th><th>存储空间</th><th>最后索引</th><th>失败原因</th><th>操作</th></tr></thead><tbody>{items.map((item) => { const isUpdating = updatingId === item.data_source_id; const indexStatus = item.index_status; const isIndexing = indexStatus === "running" || indexStatus === "queued"; return <tr key={item.data_source_id}><td><b>{item.name}</b>{!item.enabled ? <span className="base-type-tag">已停用</span> : null}</td><td><button className="table-primary-link" onClick={() => onOpen(`/knowledge-bases/${item.knowledge_base_id}`)}>{item.knowledge_base_name}</button></td><td><span className={`status-tag ${isUpdating ? "status-processing" : "status-ready"}`}>{isUpdating ? "上传中" : item.upload_status === "succeeded" ? "上传成功" : "未上传"}</span></td><td><span className={`status-tag status-${indexStatus === "failed" ? "failed" : isIndexing ? "processing" : indexStatus === "succeeded" ? "ready" : "empty"}${isIndexing ? " index-loading" : ""}`} aria-busy={isIndexing}>{INDEX_LABEL[indexStatus]}</span></td><td>{bytes(item.source_file_bytes)}</td><td>{item.last_indexed_at ? new Date(item.last_indexed_at).toLocaleString("zh-CN") : "—"}</td><td><span className="truncate-cell" title={item.failure_reason || "—"}>{item.failure_reason || "—"}</span></td><td><div className="table-actions">{item.source_type === "file" && item.allowed_actions.includes("update_file") ? <label className={`table-file-action ${!item.enabled || isIndexing || isUpdating ? "is-disabled" : ""}`}>{isUpdating ? "更新中…" : "更新文件"}<input aria-label={`更新 ${item.name}`} type="file" accept=".pdf,.docx,.txt,.md,.html,.htm,.xlsx,.csv" disabled={!item.enabled || isIndexing || isUpdating} onChange={(event) => { const file = event.target.files?.[0]; if (file) void updateFile(item, file); event.currentTarget.value = ""; }}/></label> : null}{item.allowed_actions.includes("disable") ? <button onClick={() => void act(() => api.setDataSourceEnabled(item.data_source_id, false))}>停用</button> : null}{item.allowed_actions.includes("enable") ? <button onClick={() => void act(() => api.setDataSourceEnabled(item.data_source_id, true))}>启用</button> : null}{item.allowed_actions.includes("delete") ? <button onClick={() => setConfirmDelete(item)}>删除</button> : null}</div></td></tr>; })}</tbody></table></div> : null}
    {items && (page > 0 || hasNext) ? <nav className="management-pagination" aria-label="数据源分页"><button disabled={page === 0} onClick={() => setPage((value) => Math.max(0, value - 1))}>上一页</button><span>第 {page + 1} 页</span><button disabled={!hasNext} onClick={() => setPage((value) => value + 1)}>下一页</button></nav> : null}
    {confirmDelete ? <Modal title="删除数据源" description={`将删除“${confirmDelete.name}”。关联文档必须先由知识库详情页显式删除。`} onClose={() => setConfirmDelete(null)}><footer className="modal-actions"><button className="secondary-action" onClick={() => setConfirmDelete(null)}>取消</button><button className="danger-action" onClick={() => { const item = confirmDelete; setConfirmDelete(null); void act(() => api.deleteDataSource(item.data_source_id)); }}>确认删除</button></footer></Modal> : null}
  </section>;
}
