import { useCallback, useEffect, useState } from "react";
import { api } from "../api";
import type { ConversationSummary, DataSource, DocumentCategory, DocumentInfo, DocumentVersion, IndexVersion, KnowledgeBase, User } from "../types";
import { DocumentPanel } from "./DocumentPanel";
import { Modal } from "./Modal";
import { ParsingPanel } from "./ParsingPanel";
import { KnowledgeBaseDataSourcesPanel } from "./KnowledgeBaseDataSourcesPanel";

const STATUS = { empty: "空库", processing: "处理中", ready: "可用", failed: "失败" } as const;
const VERSION_STATUS = { pending: "等待索引", indexing: "索引中", ready: "可用", failed: "失败", superseded: "历史版本" } as const;
function formatBytes(value: number) { if (!value) return "0 KB"; const divisor = value >= 1024 ** 2 ? 1024 ** 2 : 1024; return `${(value / divisor).toFixed(1)} ${divisor === 1024 ? "KB" : "MB"}`; }

export function KnowledgeBaseDetailPage({ id, onOpen }: { id: string; onOpen: (path: string) => void }) {
  const [activeTab, setActiveTab] = useState<"documents" | "data_sources" | "categories" | "parsing" | "versions" | "members" | "conversations">("documents");
  const [base, setBase] = useState<KnowledgeBase | null>(null); const [documents, setDocuments] = useState<DocumentInfo[]>([]);
  const [versions, setVersions] = useState<DocumentVersion[]>([]); const [members, setMembers] = useState<User[]>([]);
  const [dataSources, setDataSources] = useState<DataSource[]>([]);
  const [indexVersions, setIndexVersions] = useState<IndexVersion[]>([]);
  const [categories, setCategories] = useState<DocumentCategory[]>([]);
  const [categoryName, setCategoryName] = useState("");
  const [editingCategory, setEditingCategory] = useState<DocumentCategory | null>(null);
  const [categoryDraft, setCategoryDraft] = useState({ name: "", description: "", sort_order: 100 });
  const [conversations, setConversations] = useState<ConversationSummary[]>([]); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const [aclTarget, setAclTarget] = useState<{ kind: "document" | "source"; id: string; name: string; version: number; allow: string[]; deny: string[] } | null>(null);
  const [aclDraft, setAclDraft] = useState<Record<string, "inherit" | "allow" | "deny">>({});
  const [savingAcl, setSavingAcl] = useState(false);
  const [uploadProgress, setUploadProgress] = useState<{ completed: number; total: number } | null>(null);
  const load = useCallback(async () => { const detail = await api.getKnowledgeBase(id); const [docs, history, versionItems, indexVersionItems, memberItems, sourceItems, categoryItems] = await Promise.all([api.listKnowledgeBaseDocuments(id), api.listConversations(id), api.listKnowledgeBaseDocumentVersions(id), api.listKnowledgeBaseIndexVersions(id), detail.current_user_permission === "admin" ? api.listKnowledgeBaseMembers(id) : Promise.resolve([]), detail.current_user_permission === "admin" ? api.listDataSources(0, 100) : Promise.resolve([]), api.listKnowledgeBaseCategories(id)]); setBase(detail); setDocuments(docs); setConversations(history); setVersions(versionItems); setIndexVersions(indexVersionItems); setMembers(memberItems); setDataSources(sourceItems.filter((item) => item.knowledge_base_id === id)); setCategories(categoryItems); }, [id]);
  useEffect(() => { Promise.resolve().then(load).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "无法读取知识库。")); }, [load]);
  const upload = async (files: File[]) => { setBusy(true); setError(""); setUploadProgress({ completed: 0, total: files.length }); const failed: string[] = []; try { for (const [index, file] of files.entries()) { try { await api.uploadKnowledgeBaseDocument(id, file); } catch { failed.push(file.name); } finally { setUploadProgress({ completed: index + 1, total: files.length }); } } await load(); if (failed.length) setError(`以下文件上传失败：${failed.join("、")}`); } finally { setBusy(false); setUploadProgress(null); } };
  const remove = async (documentId: string) => { setError(""); try { await api.deleteKnowledgeBaseDocument(id, documentId); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "删除失败。"); } };
  const updateMetadata = async (documentId: string, category: string, tags: string[]) => { setError(""); try { const updated = await api.updateKnowledgeBaseDocumentMetadata(id, documentId, { category, tags }); setDocuments((items) => items.map((item) => item.document_id === documentId ? updated : item)); } catch (reason) { setError(reason instanceof Error ? reason.message : "元数据更新失败。"); throw reason; } };
  const batchCategory = async (documentIds: string[], categoryId: string) => { setBusy(true); setError(""); try { await api.batchAssignDocumentCategory(id, documentIds, categoryId); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "批量归类失败。"); throw reason; } finally { setBusy(false); } };
  const createCategory = async () => { const name = categoryName.trim(); if (!name) return; setBusy(true); try { await api.createKnowledgeBaseCategory(id, { name, description: "", sort_order: 100 }); setCategoryName(""); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "创建分类失败。"); } finally { setBusy(false); } };
  const toggleCategory = async (item: DocumentCategory) => { setBusy(true); try { await api.updateKnowledgeBaseCategory(id, item.category_id, { name: item.name, description: item.description, sort_order: item.sort_order, active: !item.active }); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "更新分类失败。"); } finally { setBusy(false); } };
  const openCategoryEditor = (item: DocumentCategory) => { setEditingCategory(item); setCategoryDraft({ name: item.name, description: item.description, sort_order: item.sort_order }); };
  const saveCategory = async () => { if (!editingCategory || !categoryDraft.name.trim()) return; setBusy(true); setError(""); try { await api.updateKnowledgeBaseCategory(id, editingCategory.category_id, { ...categoryDraft, name: categoryDraft.name.trim(), description: categoryDraft.description.trim(), active: editingCategory.active }); await load(); setEditingCategory(null); } catch (reason) { setError(reason instanceof Error ? reason.message : "更新分类失败。"); } finally { setBusy(false); } };
  const deleteCategory = async (item: DocumentCategory) => { setBusy(true); try { await api.deleteKnowledgeBaseCategory(id, item.category_id); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "删除分类失败。"); } finally { setBusy(false); } };
  const openAcl = (target: typeof aclTarget) => { if (!target) return; const draft: Record<string, "inherit" | "allow" | "deny"> = {}; members.forEach((member) => { draft[member.user_id] = target.deny.includes(member.user_id) ? "deny" : target.allow.includes(member.user_id) ? "allow" : "inherit"; }); setAclDraft(draft); setAclTarget(target); };
  const saveAcl = async () => { if (!aclTarget) return; setSavingAcl(true); setError(""); const policy = { allow_user_ids: Object.entries(aclDraft).filter(([, value]) => value === "allow").map(([userId]) => userId), deny_user_ids: Object.entries(aclDraft).filter(([, value]) => value === "deny").map(([userId]) => userId) }; try { if (aclTarget.kind === "document") await api.updateKnowledgeBaseDocumentAcl(id, aclTarget.id, policy); else await api.updateDataSourceAcl(aclTarget.id, policy); await load(); setAclTarget(null); } catch (reason) { setError(reason instanceof Error ? reason.message : "ACL 更新失败。"); } finally { setSavingAcl(false); } };
  return <section className="product-page"><div className="detail-toolbar"><button className="back-link" onClick={() => onOpen("/knowledge-bases")}>← 返回知识库</button>{base ? <button className="primary-action" onClick={() => onOpen(`/chat?knowledge_base_id=${id}`)}>在此知识库提问 →</button> : null}</div>{error ? <div className="error-banner" role="alert">{error}</div> : null}{base ? <>
    <section className="knowledge-detail-summary"><div><span>名称</span><strong>{base.name}</strong><em className="base-type-tag">{base.is_default ? "默认知识库" : "独立知识库"}</em></div><div><span>描述</span><strong>{base.description || "—"}</strong></div><div><span>文件占用</span><strong>{formatBytes(base.source_file_bytes)}</strong></div><div><span>索引状态</span><strong><i className={`status-tag status-${base.index_status}`}>{STATUS[base.index_status]}</i></strong></div><div><span>更新时间</span><strong>{new Date(base.updated_at).toLocaleString("zh-CN")}</strong></div></section>
    <div className="detail-tabs" role="tablist" aria-label="知识库详情">
      <button role="tab" aria-selected={activeTab === "documents"} onClick={() => setActiveTab("documents")}>资料 <span>{documents.length}</span></button>
      <button role="tab" aria-selected={activeTab === "data_sources"} onClick={() => setActiveTab("data_sources")}>数据源 <span>{dataSources.length}</span></button>
      <button role="tab" aria-selected={activeTab === "categories"} onClick={() => setActiveTab("categories")}>分类管理 <span>{categories.length}</span></button>
      <button role="tab" aria-selected={activeTab === "parsing"} onClick={() => setActiveTab("parsing")}>解析与切片 <span>{versions.filter((item) => item.parse_status === "ready").length}</span></button>
      <button role="tab" aria-selected={activeTab === "versions"} onClick={() => setActiveTab("versions")}>版本治理 <span>{versions.length}</span></button>
      <button role="tab" aria-selected={activeTab === "members"} onClick={() => setActiveTab("members")}>权限边界 <span>{members.length}</span></button>
      <button role="tab" aria-selected={activeTab === "conversations"} onClick={() => setActiveTab("conversations")}>会话 <span>{conversations.length}</span></button>
    </div>
    <div className="detail-tab-panel" role="tabpanel">
      {activeTab === "documents" ? <DocumentPanel documents={documents} categories={categories} loading={busy} uploadProgress={uploadProgress} onUpload={upload} onDelete={remove} onUpdateMetadata={updateMetadata} onBatchCategory={batchCategory}/> : null}
      {activeTab === "data_sources" ? <KnowledgeBaseDataSourcesPanel knowledgeBaseId={id} items={dataSources} categories={categories} onRefresh={load}/> : null}
      {activeTab === "categories" ? <section className="category-governance"><div className="category-create"><input aria-label="新分类名称" value={categoryName} maxLength={64} placeholder="输入分类名称" onChange={(event) => setCategoryName(event.target.value)}/><button className="primary-action" type="button" disabled={busy || !categoryName.trim()} onClick={() => void createCategory()}>新建分类</button></div><div className="category-list">{categories.map((item) => <div key={item.category_id}><span><strong>{item.name}</strong><small>{item.document_count} 份资料 · 排序 {item.sort_order}{item.active ? "" : " · 已停用"}</small>{item.description ? <small>{item.description}</small> : null}</span><div><button type="button" disabled={busy} onClick={() => openCategoryEditor(item)}>编辑</button><button type="button" disabled={busy || item.is_system} onClick={() => void toggleCategory(item)}>{item.active ? "停用" : "启用"}</button><button className="table-danger-action" type="button" disabled={busy || item.is_system || item.document_count > 0} title={item.document_count > 0 ? "请先迁移资料" : ""} onClick={() => void deleteCategory(item)}>删除</button></div></div>)}</div></section> : null}
      {activeTab === "parsing" ? <ParsingPanel knowledgeBaseId={id} versions={versions} canManage={base.current_user_permission === "admin"} onRefresh={load}/> : null}
      {activeTab === "versions" ? <section className="version-governance"><h3>Index Version</h3>{indexVersions.length ? <div className="index-version-table"><table className="governance-table"><thead><tr><th>版本</th><th>状态</th><th>Parser / Chunking</th><th>Embedding</th><th>质量报告</th></tr></thead><tbody>{indexVersions.map((item) => <tr key={item.index_version_id}><td><strong>{item.index_version_id}</strong><small>{item.config_fingerprint.slice(0, 12)}</small></td><td><span className={`status-tag status-${item.status === "failed" ? "failed" : item.status === "building" ? "processing" : "ready"}`}>{item.status}</span></td><td>{item.parser_version}<small>{item.chunking_version}</small></td><td>{item.embedding_model}<small>{item.embedding_dimension} 维</small></td><td>{item.evaluation_report_id || "待验证"}</td></tr>)}</tbody></table></div> : <p className="empty-copy">还没有 Index Version。</p>}<h3>Document Version</h3>{versions.length ? <div className="version-list">{versions.map((item) => <article key={item.document_version_id}><div><b>{item.filename}</b><span>V{item.version_number}{item.is_current ? <em>当前版本</em> : null}</span></div><div><span>{formatBytes(item.source_file_bytes)} · {item.content_sha256.slice(0, 10)}</span><span>{item.parser_name || "旧版解析"} {item.parser_version || "legacy"} · {item.chunking_version || "旧版切片"} · {item.node_count} 节点 / {item.parsed_chunk_count} Chunk</span><span>{new Date(item.created_at).toLocaleString("zh-CN")}</span></div><strong className={`status-tag status-${item.parse_status === "failed" || item.status === "failed" ? "failed" : item.parse_status !== "ready" || item.status === "indexing" || item.status === "pending" ? "processing" : "ready"}`}>{item.parse_status === "failed" ? item.parse_failure_code || "解析失败" : item.parse_status !== "ready" ? `解析${item.parse_status}` : VERSION_STATUS[item.status]}</strong>{item.failure_reason ? <small title={item.failure_reason}>{item.failure_reason}</small> : null}</article>)}</div> : <p className="empty-copy">还没有 Document Version。</p>}</section> : null}
      {activeTab === "members" ? <section className="surface-card acl-governance">{base.current_user_permission === "admin" ? <><p className="acl-note">Deny 优先；未配置时继承知识库成员权限。ACL 更新后立即影响下一次检索。</p><h3>数据源 ACL</h3>{dataSources.length ? <div className="acl-table">{dataSources.map((item) => <div className="acl-row" key={item.data_source_id}><span><strong>{item.name}</strong><small>版本 {item.acl_version} · Allow {item.allow_user_ids.length} · Deny {item.deny_user_ids.length}</small></span><button type="button" onClick={() => openAcl({ kind: "source", id: item.data_source_id, name: item.name, version: item.acl_version, allow: item.allow_user_ids, deny: item.deny_user_ids })}>配置</button></div>)}</div> : <p className="empty-copy">当前知识库没有独立数据源。</p>}<h3>文档 ACL</h3>{documents.length ? <div className="acl-table">{documents.map((item) => <div className="acl-row" key={item.document_id}><span><strong>{item.filename}</strong><small>版本 {item.acl_version} · {item.sensitivity} · Allow {item.allow_user_ids.length} · Deny {item.deny_user_ids.length}</small></span><button type="button" onClick={() => openAcl({ kind: "document", id: item.document_id, name: item.filename, version: item.acl_version, allow: item.allow_user_ids, deny: item.deny_user_ids })}>配置</button></div>)}</div> : <p className="empty-copy">当前知识库没有文档。</p>}</> : <p className="empty-copy">你拥有该知识库的使用权限；ACL 策略仅管理员可见。</p>}</section> : null}
      {activeTab === "conversations" ? <section className="surface-card">{conversations.length ? <div className="compact-list">{conversations.map((item) => <button key={item.conversation_id} onClick={() => onOpen(`/chat/${item.conversation_id}?knowledge_base_id=${id}`)}><span><b>{item.title}</b><small>{new Date(item.updated_at).toLocaleString("zh-CN")}</small></span><em>{item.turn_count} 轮</em></button>)}</div> : <p className="empty-copy">还没有会话。</p>}</section> : null}
    </div>
  </> : null}{editingCategory ? <Modal title="编辑分类" description={editingCategory.is_system ? "系统分类名称不可修改" : "修改后立即用于资料筛选"} onClose={() => { if (!busy) setEditingCategory(null); }}><form className="metadata-form" onSubmit={(event) => { event.preventDefault(); void saveCategory(); }}><label>名称<input value={categoryDraft.name} maxLength={64} disabled={editingCategory.is_system} onChange={(event) => setCategoryDraft((current) => ({ ...current, name: event.target.value }))}/></label><label>描述<textarea value={categoryDraft.description} maxLength={300} rows={3} onChange={(event) => setCategoryDraft((current) => ({ ...current, description: event.target.value }))}/></label><label>排序<input type="number" min={0} max={10000} value={categoryDraft.sort_order} onChange={(event) => setCategoryDraft((current) => ({ ...current, sort_order: Number(event.target.value) }))}/></label><footer className="modal-actions"><button className="secondary-action" type="button" disabled={busy} onClick={() => setEditingCategory(null)}>取消</button><button className="primary-action" type="submit" disabled={busy || !categoryDraft.name.trim()}>{busy ? "保存中…" : "保存"}</button></footer></form></Modal> : null}{aclTarget ? <Modal title="配置 ACL" description={`${aclTarget.name} · 当前版本 ${aclTarget.version}`} onClose={() => { if (!savingAcl) setAclTarget(null); }}><div className="acl-editor">{members.length ? members.map((member) => <label key={member.user_id}><span><strong>{member.display_name}</strong><small>{member.username}</small></span><select aria-label={`${member.display_name} ACL`} value={aclDraft[member.user_id] || "inherit"} onChange={(event) => setAclDraft((current) => ({ ...current, [member.user_id]: event.target.value as "inherit" | "allow" | "deny" }))}><option value="inherit">继承</option><option value="allow">Allow</option><option value="deny">Deny</option></select></label>) : <p className="empty-copy">知识库尚未授权成员，无需配置细粒度 ACL。</p>}</div><footer className="modal-actions"><button className="secondary-action" type="button" disabled={savingAcl} onClick={() => setAclTarget(null)}>取消</button><button className="primary-action" type="button" disabled={savingAcl || !members.length} onClick={() => void saveAcl()}>{savingAcl ? "保存中…" : "保存并立即生效"}</button></footer></Modal> : null}</section>;
}
